### ISSUE TITLE
Why is the async API protected?

### ISSUE THREAD

**Issue by cgddrd-gardin** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#11]
Hi, 

Whats the reason for making the async functions of the Python StreamManagerAPI protected, and only declaring a synchronous public API? 

Is there any specific reason why I couldn't use the protected async functions in my async Greengrass component?

Many thanks in advance,

**Comment by MikeDombo** [comment]
Hi Connor,
You're free to use those APIs if you prefer (and you're running your own async event loop already). They're just protected to keep the public API surface smaller, since at least at the time this SDK was originally written, asyncio had very limited uptake.

**Comment by cgddrd-gardin** [comment]
Thanks for the quick response @MikeDombo, that all makes sense!
