### ISSUE TITLE
Component Dependency Drift

### ISSUE THREAD

**Issue by Texas-Tim** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#13]
I'm working on a project to send IoT data from clients to the GG Core Device through MQTT and then to AWS through Stream Manager. I've been using the Python example [here](https://docs.aws.amazon.com/greengrass/v2/developerguide/use-stream-manager-in-custom-components.html) which uses the [stream_manager.py](https://github.com/aws-greengrass/aws-greengrass-stream-manager-sdk-python/blob/main/samples/stream_manager_s3.py) file as a template.

Here's the issue: GreenGrass Components use different path locations to dependencies than my local scripts.

Since I want my customer to be able to follow along, I'm recording my steps. Thus, as a replicable example, I spun up a new Cloud9 t3.large instance using Ubuntu 18.04 LTS.

I installed python3.7 due to an issue with resolving cbor2 in the component using the default python3.6, but I get the log error: "com.example.StreamManagerS3Python: stderr. ModuleNotFoundError: No module named 'stream_manager'" As you can probably guess, I have definitely installed stream_manager and I can prove it by testing the example template locally.

When printing out the python3 -V during the recipe and logging the results, I noticed that the component treats system paths differently then a local python script. Say I install python3.7 for example. python3 will default to python3.7 locally, or I can force it to, unless I'm running python3 in the component, then it defaults to python3.6 for some reason. I imagine I'm this is why I'm getting this error as stream_manager is not installed relative to the GreenGrass Device

Resolution: I can add stream_manager to my requirements.txt file during the component BUILD phase which will install stream_manager to whatever python path it decides to use. While this "works" it's unsatisfying as I should be able to treat my GreenGrass device as its own device and not two separate devices. I essentially have to "guess" what the default for the GreenGrass device is from a runtime perspective. How do I manage the dependencies for GreenGrass when setting it up in a way that I can easily replicate it for someone else to follow?

**Comment by MikeDombo** [comment]
What is your full Greengrass component recipe contents?

The instructions have you download this SDK and include it as part of the component artifacts, then using the PYTHONPATH environment variable, it tells Python where to find the SDK. This is guaranteed to work and does not rely on installing the stream manager SDK to Python on the system.

Greengrass does not choose what Python to run, that is your choice depending on what command you put in the recipe and what is installed on the system. If you want to run a particular Python version, you can always do that by specifying the full path to the binary that you want Greengrass to run in the recipe, though in general this should not be necessary.

**Comment by Texas-Tim** [comment]
Here's my recipe
```json
{
  "RecipeFormatVersion": "2020-01-25",
  "ComponentName": "com.example.StreamManagerS3Python",
  "ComponentVersion": "1.0.0",
  "ComponentDescription": "Uses stream manager to upload a file to an S3 bucket.",
  "ComponentPublisher": "Amazon",
  "ComponentDependencies": {
    "aws.greengrass.StreamManager": {
      "VersionRequirement": "^2.0.0"
    }
  },
  "Manifests": [
    {
      "Platform": {
        "os": "linux"
      },
      "Lifecycle": {
        "Install": "pip3 install --user -r /home/ubuntu/environment/GreengrassCore/requirements.txt",
        "Run": "export PYTHONPATH=$PYTHONPATH:/home/ubuntu/environment/GreengrassCore/stream_manager_sdk; python3 {artifacts:path}/stream_manager_s3.py"
      },
      "Artifacts": [
        {
          "URI": "s3://stream-manager-test-bucket/artifacts/com.example.StreamManagerS3Python/1.0.0/stream_manager_sdk.zip",
          "Unarchive": "ZIP"
        },
        {
          "URI": "s3://stream-manager-test-bucket/artifacts/com.example.StreamManagerS3Python/1.0.0/stream_manager_s3.py"
        },
        {
          "URI": "s3://stream-manager-test-bucket/artifacts/com.example.StreamManagerS3Python/1.0.0/requirements.txt"
        }
      ]
    }
  ]
}
```

**Comment by Texas-Tim** [comment]
I have stream_manager_sdk.zip at that location, should I unzip it? I think I tried that but maybe missed something.

As for determining the Python runtime, I choose in the recipe to run python3, but GreenGrass might default to python3.6 when I want to use python3.7. This is just one example. The real issue I have is running the StreamManager module. After installing using `pip3 install stream_manager`, the GG component is unable to find stream_manager and throws the error

**Comment by MikeDombo** [comment]
Your recipe does not match what is provided in the example. The example is correct, you must follow it, using `{artifacts:path}` and `{artifacts:decompressedPath}`

**Comment by Texas-Tim** [comment]
Yes that worked, at some point I must have removed it while testing.

Before I close this issue, could you perhaps share with me another mystery? During setup, I ran into a bug where the component would not resolve to the S3 endpoint. I fixed this by creating a new S3 bucket in the same Region as the Thing.  I know that permissions for cross-account streams can be difficult or impossible but I would not have considered that the same would be true for cross-region

**Comment by Texas-Tim** [comment]
I've checked all the permissions and as far as I can tell they all allow S3 actions and none specify a specific region. I can open a new issue if necessary

**Comment by MikeDombo** [comment]
The bucket must be in the same region as the Greengrass device/component. Cross-region buckets are not supported.
