### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by ppbrown** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#14]
For some reason, 

https://aws-greengrass.github.io/aws-greengrass-stream-manager-sdk-python/_apidoc/stream_manager.html

only has documentation for SUBmodules. It doesnt have docs for the BASIC api.
For example, there are zero docs for StreamManagerClient  ?!?!?!

**Comment by MikeDombo** [comment]
The documentation has no problem. The client documentation is here. https://aws-greengrass.github.io/aws-greengrass-stream-manager-sdk-python/_apidoc/stream_manager.streammanagerclient.html#stream_manager.streammanagerclient.StreamManagerClient

Hope this helps

**Comment by MikeDombo** [comment]
Full documentation is also available in the AWS docs https://docs.aws.amazon.com/greengrass/v2/developerguide/manage-data-streams.html.
