### ISSUE TITLE
Is there any way to write in Stream Manager in batches?

### ISSUE THREAD

**Issue by acantalejo-keepler** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#17]
Hello!
I only see the "append_message" function that writes one at a time.
I need faster writing speed in the stream

Thanks!!

**Comment by MikeDombo** [comment]
That is the only API to write to streams.
You're free to write anything into the stream, it can be as big as you like, subject to restrictions on where you are exporting the stream data.

You can append data from multiple threads, but the bottleneck is almost certainly your disk write speed or the export destination upload speed.
