### ISSUE TITLE
StreamManager stream behaviour on full

### ISSUE THREAD

**Issue by tomikpik** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#21]
Hi, I have a question regarding the stream behaviour and how to configure it properly.
The desired behaviour is following:
- data are being produced by the device and appended to the stream (with RejectNewData strategy)
- there is a kinesis export definition so the data are eventually uploaded to the Kinesis

Under normal conditions, I'd expect the data to be continuously uploaded and overwritten by new ones once uploaded. 

In the case of a connectivity outage, the stream would eventually get filled in and start rejecting new "append" operations.
Once the connectivity is restored I'd expect that the backup to the cloud is restored. 

**Stream info:**
```
MessageStreamDefinition(
    name=self._stream_name,
    max_size=max_size, # 128MB
    stream_segment_size=segment_size, # 16MB
    time_to_live_millis=..., # 3 days
    strategy_on_full=StrategyOnFull.RejectNewData,
    persistence=Persistence.File,
    flush_on_write=False,
    export_definition=ExportDefinition(
        kinesis=[KinesisConfig(
            identifier=str(uuid.uuid4()),
            kinesis_stream_name=kinesis_stream_name,
            batch_interval_millis=61000,
            batch_size=1
        )],
        iot_analytics=None,
        iot_sitewise=None,
        s3_task_executor=None
    )
)
```

### **Problem description**
The observed behaviour for this configuration is that even if the device is online the already uploaded data are not deleted (probably caused by the 3 day TTL) which results in the stream being filled in and rejecting new messages even if they were successfully uploaded (exported bytes metric corresponds to the stream size).  

How are the TTL and ExportDefinition connected? If both are configured how exactly does it work?
Multiple situations can occur:

**Situation 1:**
- TTL: not exceeded yet
- Exported: no
Expected behaviour: the record is persisted in the stream, ready for export, should not be deleted yet 

**Situation 2:**
- TTL: exceeded
- Exported: no
Expected behaviour: the record is persisted in the stream, ready for export once it is possible, **should not be deleted yet** 

**Situation 3:**
- TTL: not exceeded
- Exported: yes
Expected behaviour: the record is still persisted, waiting for TTL to be exceeded

**Situation 4:**
- TTL: exceeded
- Exported: yes
Expected behaviour: the record can be overwritten by new records 

### **Questions:**
Could you please take a look at the described situations and confirm/deny if the actual behaviour is the same as I've described as expected?

Can you please advise how to ensure that in Situation 2 the data are uploaded once it is possible (connectivity is restored)?

How to make sure (in Situation 3) that records that were already uploaded (and their TTL is not exceeded yet) are not preventing new ones from being appended to stream?

Thank you
Tom

**Comment by MikeDombo** [comment]
Hello Tom,

Stream manager does not delete data which has been uploaded, so this is why you see that the stream can be full even when all data is uploaded. Data is only deleted according to the TTL policy and the behavior when full policy.

> How are the TTL and ExportDefinition connected?

They are not connected.

**Comment by tomikpik** [comment]
Hi Mike, thank you for your response. That unfortunately seems there is no way to guarantee consistency.
Is there any suggestion from your side to achieve the desired behaviour using the StreamManager or should I use a different technology?

I'll briefly summarize the situation and the behaviour I'd like to achieve.
- Device is producing data, data are appended to a SM stream, eventually exported/uploaded to the Kinesis
- Let's say a network problem occurs - In this case, the device shoud buffer data in the SM stream as long as possible until it is full (specified by the max stream size) - exception during the "append" call would stop the "processing"/creation of new records
- Once the connectivity is restored, all the buffered records will be exported to the Kinesis, and space in the stream will be freed
- Processing/creation of new records is resumed

The main point is that I'd like to have a consecutive block of records that is as long as possible and stop the creation of new records when we're not able to store or upload them. The processing/creation of new records should only be resumed once it is possible to upload/export them.

Thank you very much 🙏  
Tom

**Comment by MikeDombo** [comment]
Stream manager does let you query the stream to know what data has been exported, so you could query it prior to putting in new data to see if the export is keeping up or if it is falling behind. That's the only suggestion I can make for your case. The idea with the current implementation stream manager is that newer data is generally going to be more useful, so older data should be overwritten if it cannot be uploaded before the stream fills up.
