### ISSUE TITLE
Release the Stream Manager SDK into the Python Package Index (PyPI)

### ISSUE THREAD

**Issue by japsu** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#3]
There is no reason not to have Stream Manager SDK listed on pypi.org, the central index for Python packages.

Having Stream Manager SDK listed on pypi.org would make installing it easier (see #2). Assume the name of the package were `streammanagersdk`:

    pip install streammanagersdk

**Comment by cgddrd-gardin** [comment]
I'd absolutely second this - firewalls and proxy servers don't always whitelist github, which prevents us from installing correctly, and I don't want to have to request for Github to be whitelisted just for this. Now this is in production, and an officially supported feature of Greengrass V2, please can this be published to Pypi like literally every other production Python package?

**Comment by MikeDombo** [comment]
This SDK is part of greengrasssdk, so you can install that from pip https://pypi.org/project/greengrasssdk/. `pip install greengrasssdk`

**Comment by cgddrd-gardin** [comment]
Thanks @MikeDombo, consider me educated!

**Comment by Cyril-Lagrange** [comment]
I'm confused about the information published on the pypi page for greengrasssdk. It does not list greeen grass core 2.0 as compatible with version 1.6 of the sdk.

**Comment by MikeDombo** [comment]
Completed, https://pypi.org/project/stream_manager/

**Comment by cgddrd-gardin** [comment]
This is v. cool - thanks @MikeDombo!
