### ISSUE TITLE
Add link to documentation in main README.md

### ISSUE THREAD

**Issue by gadams999** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#7]
Currently the link to the documentation for Stream Manager is in the _About_ description of the repo. Most viewers will parse the main README and not find a link to the documentation.

Suggest adding a short description and link to the documentation directly within the README.

**Comment by jbutler** [comment]
Thanks for the suggestion, Gavin! I've updated the README to include this and it will be released with the next code push.

**Comment by jbutler** [comment]
Hey Gavin - version 1.1.1 has just been released, along with a README update. Thanks again for the suggestion
