### ISSUE TITLE
How to keep authentication from within a container?

### ISSUE THREAD

**Issue by Minipada** [aws-greengrass/aws-greengrass-stream-manager-sdk-python#8]
I'm running a container with network_mode host and running the stream manager client from within.
The stream manager itself runs on the host natively.

The client, from the container fails to connect and the only way to make it work is to set **STREAM_MANAGER_AUTHENTICATE_CLIENT** to false.
Is there a workaround to keep authentication?
Thanks

**Comment by MikeDombo** [comment]
If the container is being run by Greengrass, then authentication will work as long as you pass through the environment variables into the container. Have a look at our documentation here: https://docs.aws.amazon.com/greengrass/v2/developerguide/run-docker-container.html#docker-container-stream-manager

If the docker container is not being executed by Greengrass, then it is not possible to have authentication enabled and work.

**Comment by Minipada** [comment]
Thanks for the prompt answer. Makes sense.
